// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package sqlc

import ()

type Coffee struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Flavor   string `json:"flavor"`
	Acidity  int16  `json:"acidity"`
	ImageSrc string `json:"image_src"`
}
